package my.app.moviesapp.ui.util

object Strings {
    val AppName = "Movie App"
    val MovieTitle = "Title"
    val Description = "Description"
    val Budget = "Budget"
    val Genres = "Genres"
    val Homepage = "Homepage"
    val Released = "Released"
    val ProductionCompanies = "Production companies"
    val Runtime = "Runtime"
    val Status = "Status"
    val MovieRemovedFromFavorites = "Movie removed from favorites"
    val MovieAddedToFavorites = "Movie added to favorites"
    val ErrorFetchingData = "Error fetching data"
    val ResultsError = "Results could not be loaded"
    val Retry = "Retry"
    val Popular = "Popular"
    val Favorites = "Favorites"
    val NoFavorites = "No favorites"
    val NotAvailable = "N/A"
    val EditNote = "Edit note"
    val Note = "Note"
    val Cancel = "Cancel"
    val Edit = "Edit"
    val NoteUpdated = "Note updated"
    val Search = "Search.."
    val Details = "Details"
    val NoSearchResults = "No search results"

    fun budgetDollar(amount: Int) = "$ $amount"
    fun minutes(duration: Int) = "$duration minutes"
}